export enum SignInActionKeys {
    SIGNING_IN = "SIGNING_IN",
    SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE = "SIGN_IN_FAILURE",
    SIGNING_OUT = "SIGNING_OUT",
    SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE",
    OTHER = "OTHER",
}

export enum UserActionKeys {
    FETCHING_USERS = "FETCHING_USERS",
    FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE",
    OTHER = "OTHER",
}
